In [31]:
import numpy as np

Creating a numpy array

In [32]:
my_list=np.array([1,2,3,5,8,13])

Other interesting ways of creating numpy arrays

In [36]:
#array within a certain range
arr_range=np.arange(1,11)
print('Elements in range 1-10: ', arr_range)

#array of zeroes
arr_zeroes=np.zeros((2,2))
print('Array of zeroes : \n', arr_zeroes)

#array of ones
arr_ones=np.ones((2,2))
print('Array of ones : \n', arr_ones)

#identity matrix
arr_id=np.eye(3)
print('Print identity matrix of order 3 : \n', arr_id)

#3*4 array filled with 4s
arr_fours=np.full((3,4),4)
print('3*4 matrix filled with 4s : \n', arr_fours)

#array filled with random values
arr_random=np.random.random((3,3))
print('3*3 matrix filled with random values : \n', arr_random)

Elements in range 1-10:  [ 1  2  3  4  5  6  7  8  9 10]
Array of zeroes : 
 [[0. 0.]
 [0. 0.]]
Array of ones : 
 [[1. 1.]
 [1. 1.]]
Print identity matrix of order 3 : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3*4 matrix filled with 4s : 
 [[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
3*3 matrix filled with random values : 
 [[0.72137722 0.83751031 0.35634636]
 [0.08213178 0.88432127 0.649964  ]
 [0.66162348 0.23358923 0.50366197]]


Exploring the datatype of elements of a np array and the shape of a np array

In [37]:
print('Datatype of matrix of ones : ',arr_ones.dtype)
print('Shape of a numpy array : ',arr_random.shape)

#Itemsize
print('Size of a single element within the ones array : ',arr_ones.dtype.itemsize)

Datatype of matrix of ones :  float64
Shape of a numpy array :  (3, 3)
Size of a single element within the ones array :  8


Using complex numbers

In [38]:
complex1=complex(4,5)
complex2=complex(-3,6)
print('Sum : ',complex1+complex2)
print('Difference : ', complex1-complex2)
print('Product : ', complex1*complex2)
print('Quotient : ', complex1/complex2)

Sum :  (1+11j)
Difference :  (7-1j)
Product :  (-42+9j)
Quotient :  (0.4-0.8666666666666667j)


Converting elements from one datatype to another

In [46]:
#converting elements of the 'ones' array to boolean datatype
print(np.bool_(arr_ones))

#converting zeroes array to float32
print(np.float32(arr_zeroes))

[[ True  True]
 [ True  True]]
[[0. 0.]
 [0. 0.]]


Manipulating array shapes